name: "✨ Feature Request"
description: "새로운 컴포넌트나 기능"
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: "제안 이유"
      description: "왜 이 기능/컴포넌트가 필요한가?"
      placeholder: "예: 프로젝트에서 반복적으로 같은 UI 패턴을 구현해야 함"
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "제안 내용"
      description: "구체적으로 어떤 기능이 어떻게 동작하면 좋을지 작성"
      placeholder: "예: Pagination 컴포넌트가 필요합니다. props: total, page, onChange..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "대안"
      description: "혹시 다른 방법은?"
